{% set name = "pygeoutils" %}
{% set version = "0.13.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoutils-{{ version }}.tar.gz
  sha256: bfc0bc87540d5de916566ca31853b3253c08387f17cac329b21089c61ed92fc6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - cytoolz
    - dask-core
    - geopandas >=0.7
    - loguru
    - netcdf4
    - numpy >=1.17
    - pygeos
    - pyproj >=2.2
    - rasterio >=1.2
    - rioxarray >=0.11
    - scipy
    - shapely >=1.8
    - ujson
    - xarray >=2022.03.0

test:
  imports:
    - pygeoutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pygeoutils
  summary: Utilities for manipulating geospatial, (Geo)JSON, and (Geo)TIFF data.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
