{% set name = "pygeoutils" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoutils-{{ version }}.tar.gz
  sha256: 9a6fef35a9d5254be1fc6115438e828fc5475bdc4bc7b9ca2da86dc854c95a5a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - aiodns
    - aiohttp
    - brotlipy
    - chardet
    - cytoolz
    - defusedxml
    - geopandas
    - nest-asyncio
    - netcdf4
    - orjson
    - owslib
    - pygeoogc
    - pyproj
    - python >=3.6
    - rasterio
    - requests
    - setuptools
    - shapely
    - simplejson
    - xarray

test:
  imports:
    - pygeoutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pygeoutils
  summary: A set of utilities for manipulating (Geo)JSON and (Geo)TIFF data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
