{% set name = "pygeoutils" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32a9762c1d6f696205602ba3014b15794344959ad9135bd328f0776f563b8f4b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - cytoolz
    - geopandas-base >=0.10
    - fiona
    - netcdf4
    - numpy >=1.21
    - pyproj >=2.2
    - rasterio >=1.2
    - rioxarray >=0.11
    - scipy
    - shapely >=2
    - ujson
    - xarray >=2023.01.0

test:
  imports:
    - pygeoutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pygeoutils
  summary: Utilities for manipulating geospatial, (Geo)JSON, and (Geo)TIFF data.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
