{% set name = "pygeoutils" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b38fca1dbbeab3b5b6eb0b647ef60fc7990b6b191d63fb2053e734c62f9db208

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - setuptools
    - geopandas
    - rasterio
    - shapely
    - xarray
    - netCDF4
    - simplejson

test:
  imports:
    - pygeoutils

about:
  home: https://github.com/cheginit/pygeoutils
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A part of Hydrodata software stack for handling geospatial data manipulations.

  description: |
    PyGeoUtils is a part of the Hydrodata suite that handles manipulation of
    (Geo)JSON and GeoTIFF objects and converting them to dataframes.
  doc_url: https://hydrodata.readthedocs.io
  dev_url: https://github.com/cheginit/pygeoutils

extra:
  recipe-maintainers:
    - cheginit
