{% set name = "pygeoutils" %}
{% set version = "0.11.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoutils-{{ version }}.tar.gz
  sha256: 4d863545fc0f4f03defb939167d3b19be15ff6ff130bbde9aa2077aec077e620

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - dask-core
    - geopandas >=0.7
    - netcdf4
    - numpy >=1.17
    - pyproj >=2.2
    - python >=3.7
    - rasterio >=1.2
    - rioxarray >=0.8
    - shapely >=1.6
    - ujson
    - xarray >=0.18

test:
  imports:
    - pygeoutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pygeoutils
  summary: A set of utilities for manipulating (Geo)JSON and (Geo)TIFF data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
