{% set name = "pygeoutils" %}
{% set version = "0.11.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoutils-{{ version }}.tar.gz
  sha256: 6eaa200311d7f660af4b356fbb2035cbe20e99718edac6669805bb017aeb38dd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - affine
    - dask-core
    - geopandas >=0.7
    - netcdf4
    - numpy >=1.17
    - pyproj >=2.2
    - python >=3.7
    - rasterio
    - shapely >=1.6
    - ujson
    - xarray >=0.17

test:
  imports:
    - pygeoutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pygeoutils
  summary: A set of utilities for manipulating (Geo)JSON and (Geo)TIFF data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
