{% set name = "pygeoutils" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoutils-{{ version }}.tar.gz
  sha256: 1dafcb5fb8f162d510e92537a7052558316e515ec18a4d7543fb35ad689b0af4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - affine
    - dask-core
    - geopandas
    - netcdf4
    - numpy
    - orjson
    - pyproj
    - python >=3.7
    - rasterio
    - shapely
    - xarray

test:
  imports:
    - pygeoutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pygeoutils
  summary: A set of utilities for manipulating (Geo)JSON and (Geo)TIFF data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
