{% set name = "pygeoutils" %}
{% set version = "0.13.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeoutils-{{ version }}.tar.gz
  sha256: 90539895708845b2b827a30c00390178a4e71b140ce245fe17286d0f3abf9b5f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - cytoolz
    - geopandas >=0.8
    - scipy
    - xarray >=2022.03.0
    - pygeos
    - rasterio >=1.2
    - dask-core
    - netcdf4
    - shapely >=1.8
    - ujson
    - pyproj >=2.2
    - numpy >=1.17
    - rioxarray >=0.11

test:
  imports:
    - pygeoutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pygeoutils
  summary: Utilities for manipulating geospatial, (Geo)JSON, and (Geo)TIFF data.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
